#[derive(Debug, PartialEq, Eq)]
pub enum T0396 {
    L99zzz,   // Local general code
    ACR,
    ANSPlus,  // ANS+ scritto come ANSPlus per conformità con Rust
    ART,
    AS4,
    AS4E,
    ATC,
    C4,
    C5,
    CAS,
    CD2,
    CDCA,
    CDCM,
    CDS,
    CE,
    CLP,
    CPTM,
    CST,
    CVX,
    DCM,
    E,
    E5,
    E6,
    E7,
    ENZC,
    FDDC,
    FDDX,
    FDK,
    HB,
    HCPCS,
    HCPT,
    HHC,
    HI,
    HL7nnnn,
    HOT,
    HPC,
    I10,
    I10P,
    I9,
    I9C,
    IBT,
    IBTnnnn,
    IC2,
    ICD10AM,
    ICD10CA,
    ICDO,
    ICS,
    ICSD,
    ISOPlus,
    ISOnnnn,
    IUPC,
    IUPP,
    JC10,
    JC8,
    JJ1017,
    LB,
    LN,
    MCD,
    MCR,
    MDDX,
    MEDC,
    MEDR,
    MEDX,
    MGPI,
    MVX,
    NDA,
    NDC,
    NIC,
    NPI,
    NUBC,
    OHA,
    POS,
    RC,
    SDM,
    SNM,
    SNM3,
    SNT,
    UC,
    UMD,
    UML,
    UPC,
    UPIN,
    USPS,
    W1,
    W2,
    W4,
    WC,
}

impl T0396 {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "99zzz" => Some(T0396::L99zzz),
            "ACR" => Some(T0396::ACR),
            "ANS+" => Some(T0396::ANSPlus),
            "ART" => Some(T0396::ART),
            "AS4" => Some(T0396::AS4),
            "AS4E" => Some(T0396::AS4E),
            "ATC" => Some(T0396::ATC),
            "C4" => Some(T0396::C4),
            "C5" => Some(T0396::C5),
            "CAS" => Some(T0396::CAS),
            "CD2" => Some(T0396::CD2),
            "CDCA" => Some(T0396::CDCA),
            "CDCM" => Some(T0396::CDCM),
            "CDS" => Some(T0396::CDS),
            "CE" => Some(T0396::CE),
            "CLP" => Some(T0396::CLP),
            "CPTM" => Some(T0396::CPTM),
            "CST" => Some(T0396::CST),
            "CVX" => Some(T0396::CVX),
            "DCM" => Some(T0396::DCM),
            "E" => Some(T0396::E),
            "E5" => Some(T0396::E5),
            "E6" => Some(T0396::E6),
            "E7" => Some(T0396::E7),
            "ENZC" => Some(T0396::ENZC),
            "FDDC" => Some(T0396::FDDC),
            "FDDX" => Some(T0396::FDDX),
            "FDK" => Some(T0396::FDK),
            "HB" => Some(T0396::HB),
            "HCPCS" => Some(T0396::HCPCS),
            "HCPT" => Some(T0396::HCPT),
            "HHC" => Some(T0396::HHC),
            "HI" => Some(T0396::HI),
            "HL7nnnn" => Some(T0396::HL7nnnn),
            "HOT" => Some(T0396::HOT),
            "HPC" => Some(T0396::HPC),
            "I10" => Some(T0396::I10),
            "I10P" => Some(T0396::I10P),
            "I9" => Some(T0396::I9),
            "I9C" => Some(T0396::I9C),
            "IBT" => Some(T0396::IBT),
            "IBTnnnn" => Some(T0396::IBTnnnn),
            "IC2" => Some(T0396::IC2),
            "ICD10AM" => Some(T0396::ICD10AM),
            "ICD10CA" => Some(T0396::ICD10CA),
            "ICDO" => Some(T0396::ICDO),
            "ICS" => Some(T0396::ICS),
            "ICSD" => Some(T0396::ICSD),
            "ISO+" => Some(T0396::ISOPlus),
            "ISOnnnn" => Some(T0396::ISOnnnn),
            "IUPC" => Some(T0396::IUPC),
            "IUPP" => Some(T0396::IUPP),
            "JC10" => Some(T0396::JC10),
            "JC8" => Some(T0396::JC8),
            "JJ1017" => Some(T0396::JJ1017),
            "LB" => Some(T0396::LB),
            "LN" => Some(T0396::LN),
            "MCD" => Some(T0396::MCD),
            "MCR" => Some(T0396::MCR),
            "MDDX" => Some(T0396::MDDX),
            "MEDC" => Some(T0396::MEDC),
            "MEDR" => Some(T0396::MEDR),
            "MEDX" => Some(T0396::MEDX),
            "MGPI" => Some(T0396::MGPI),
            "MVX" => Some(T0396::MVX),
            "NDA" => Some(T0396::NDA),
            "NDC" => Some(T0396::NDC),
            "NIC" => Some(T0396::NIC),
            "NPI" => Some(T0396::NPI),
            "NUBC" => Some(T0396::NUBC),
            "OHA" => Some(T0396::OHA),
            "POS" => Some(T0396::POS),
            "RC" => Some(T0396::RC),
            "SDM" => Some(T0396::SDM),
            "SNM" => Some(T0396::SNM),
            "SNM3" => Some(T0396::SNM3),
            "SNT" => Some(T0396::SNT),
            "UC" => Some(T0396::UC),
            "UMD" => Some(T0396::UMD),
            "UML" => Some(T0396::UML),
            "UPC" => Some(T0396::UPC),
            "UPIN" => Some(T0396::UPIN),
            "USPS" => Some(T0396::USPS),
            "W1" => Some(T0396::W1),
            "W2" => Some(T0396::W2),
            "W4" => Some(T0396::W4),
            "WC" => Some(T0396::WC),
            _ => None,
        }
    }
}


pub struct CodedElement {
    pub ce1: String,
    pub ce2: String,
    pub ce3: T0396,
    pub ce4: String,
    pub ce5: String,
    pub ce6: T0396,

}
