#[derive(Debug, PartialEq, Eq)]
pub enum T0396 {
    L99zzz,   // Local general code
    ACR,
    ANSPlus,  // ANS+ scritto come ANSPlus per conformità con Rust
    ART,
    AS4,
    AS4E,
    ATC,
    C4,
    C5,
    CAS,
    CD2,
    CDCA,
    CDCM,
    CDS,
    CE,
    CLP,
    CPTM,
    CST,
    CVX,
    DCM,
    E,
    E5,
    E6,
    E7,
    ENZC,
    FDDC,
    FDDX,
    FDK,
    HB,
    HCPCS,
    HCPT,
    HHC,
    HI,
    HL7nnnn,
    HOT,
    HPC,
    I10,
    I10P,
    I9,
    I9C,
    IBT,
    IBTnnnn,
    IC2,
    ICD10AM,
    ICD10CA,
    ICDO,
    ICS,
    ICSD,
    ISOPlus,
    ISOnnnn,
    IUPC,
    IUPP,
    JC10,
    JC8,
    JJ1017,
    LB,
    LN,
    MCD,
    MCR,
    MDDX,
    MEDC,
    MEDR,
    MEDX,
    MGPI,
    MVX,
    NDA,
    NDC,
    NIC,
    NPI,
    NUBC,
    OHA,
    POS,
    RC,
    SDM,
    SNM,
    SNM3,
    SNT,
    UC,
    UMD,
    UML,
    UPC,
    UPIN,
    USPS,
    W1,
    W2,
    W4,
    WC,
}

impl T0076 {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "99zzz" => Some(T0076::L99zzz),
            "ACR" => Some(T0076::ACR),
            "ANS+" => Some(T0076::ANSPlus),
            "ART" => Some(T0076::ART),
            "AS4" => Some(T0076::AS4),
            "AS4E" => Some(T0076::AS4E),
            "ATC" => Some(T0076::ATC),
            "C4" => Some(T0076::C4),
            "C5" => Some(T0076::C5),
            "CAS" => Some(T0076::CAS),
            "CD2" => Some(T0076::CD2),
            "CDCA" => Some(T0076::CDCA),
            "CDCM" => Some(T0076::CDCM),
            "CDS" => Some(T0076::CDS),
            "CE" => Some(T0076::CE),
            "CLP" => Some(T0076::CLP),
            "CPTM" => Some(T0076::CPTM),
            "CST" => Some(T0076::CST),
            "CVX" => Some(T0076::CVX),
            "DCM" => Some(T0076::DCM),
            "E" => Some(T0076::E),
            "E5" => Some(T0076::E5),
            "E6" => Some(T0076::E6),
            "E7" => Some(T0076::E7),
            "ENZC" => Some(T0076::ENZC),
            "FDDC" => Some(T0076::FDDC),
            "FDDX" => Some(T0076::FDDX),
            "FDK" => Some(T0076::FDK),
            "HB" => Some(T0076::HB),
            "HCPCS" => Some(T0076::HCPCS),
            "HCPT" => Some(T0076::HCPT),
            "HHC" => Some(T0076::HHC),
            "HI" => Some(T0076::HI),
            "HL7nnnn" => Some(T0076::HL7nnnn),
            "HOT" => Some(T0076::HOT),
            "HPC" => Some(T0076::HPC),
            "I10" => Some(T0076::I10),
            "I10P" => Some(T0076::I10P),
            "I9" => Some(T0076::I9),
            "I9C" => Some(T0076::I9C),
            "IBT" => Some(T0076::IBT),
            "IBTnnnn" => Some(T0076::IBTnnnn),
            "IC2" => Some(T0076::IC2),
            "ICD10AM" => Some(T0076::ICD10AM),
            "ICD10CA" => Some(T0076::ICD10CA),
            "ICDO" => Some(T0076::ICDO),
            "ICS" => Some(T0076::ICS),
            "ICSD" => Some(T0076::ICSD),
            "ISO+" => Some(T0076::ISOPlus),
            "ISOnnnn" => Some(T0076::ISOnnnn),
            "IUPC" => Some(T0076::IUPC),
            "IUPP" => Some(T0076::IUPP),
            "JC10" => Some(T0076::JC10),
            "JC8" => Some(T0076::JC8),
            "JJ1017" => Some(T0076::JJ1017),
            "LB" => Some(T0076::LB),
            "LN" => Some(T0076::LN),
            "MCD" => Some(T0076::MCD),
            "MCR" => Some(T0076::MCR),
            "MDDX" => Some(T0076::MDDX),
            "MEDC" => Some(T0076::MEDC),
            "MEDR" => Some(T0076::MEDR),
            "MEDX" => Some(T0076::MEDX),
            "MGPI" => Some(T0076::MGPI),
            "MVX" => Some(T0076::MVX),
            "NDA" => Some(T0076::NDA),
            "NDC" => Some(T0076::NDC),
            "NIC" => Some(T0076::NIC),
            "NPI" => Some(T0076::NPI),
            "NUBC" => Some(T0076::NUBC),
            "OHA" => Some(T0076::OHA),
            "POS" => Some(T0076::POS),
            "RC" => Some(T0076::RC),
            "SDM" => Some(T0076::SDM),
            "SNM" => Some(T0076::SNM),
            "SNM3" => Some(T0076::SNM3),
            "SNT" => Some(T0076::SNT),
            "UC" => Some(T0076::UC),
            "UMD" => Some(T0076::UMD),
            "UML" => Some(T0076::UML),
            "UPC" => Some(T0076::UPC),
            "UPIN" => Some(T0076::UPIN),
            "USPS" => Some(T0076::USPS),
            "W1" => Some(T0076::W1),
            "W2" => Some(T0076::W2),
            "W4" => Some(T0076::W4),
            "WC" => Some(T0076::WC),
            _ => None,
        }
    }
}


pub struct CodedElement {
    pub ce1: String,
    pub ce2: String,
    pub ce3: T0396,
    pub ce4: String,
    pub ce5: String,
    pub ce6: T0396,

}
