use crate::codedelement::CodedElement;


pub enum T0104 {
    V2_0,
    V2_0D,
    V2_1,
    V2_2,
    V2_3,
    V2_3_1,
    V2_4,
    V2_5
}


pub enum T0399 {
    ABW,
    AFG,
    AGO,
    AIA,
    ALA,
    ALB,
    AND,
    ARE,
    ARG,
    ARM,
    ASM,
    ATA,
    ATF,
    ATG,
    AUS,
    AUT,
    AZE,
    BDI,
    BEL,
    BEN,
    BES,
    BFA,
    BGD,
    BGR,
    BHR,
    BHS,
    BIH,
    BLM,
    BLR,
    BLZ,
    BMU,
    BOL,
    BRA,
    BRB,
    BRN,
    BTN,
    BVT,
    BWA,
    CAF,
    CAN,
    CCK,
    CHE,
    CHL,
    CHN,
    CIV,
    CMR,
    COD,
    COG,
    COK,
    COL,
    COM,
    CPV,
    CRI,
    CUB,
    CUW,
    CXR,
    CYM,
    CYP,
    CZE,
    DEU,
    DJI,
    DMA,
    DNK,
    DOM,
    DZA,
    ECU,
    EGY,
    ERI,
    ESH,
    ESP,
    EST,
    ETH,
    FIN,
    FJI,
    FLK,
    FRA,
    FRO,
    FSM,
    GAB,
    GBR,
    GEO,
    GGY,
    GHA,
    GIB,
    GIN,
    GLP,
    GMB,
    GNB,
    GNQ,
    GRC,
    GRD,
    GRL,
    GTM,
    GUF,
    GUM,
    GUY,
    HKG,
    HMD,
    HND,
    HRV,
    HTI,
    HUN,
    IDN,
    IMN,
    IND,
    IOT,
    IRL,
    IRN,
    IRQ,
    ISL,
    ISR,
    ITA,
    JAM,
    JEY,
    JOR,
    JPN,
    KAZ,
    KEN,
    KGZ,
    KHM,
    KIR,
    KNA,
    KOR,
    KWT,
    LAO,
    LBN,
    LBR,
    LBY,
    LCA,
    LIE,
    LKA,
    LSO,
    LTU,
    LUX,
    LVA,
    MAC,
    MAF,
    MAR,
    MCO,
    MDA,
    MDG,
    MDV,
    MEX,
    MHL,
    MKD,
    MLI,
    MLT,
    MMR,
    MNE,
    MNG,
    MNP,
    MOZ,
    MRT,
    MSR,
    MTQ,
    MUS,
    MWI,
    MYS,
    MYT,
    NAM,
    NCL,
    NER,
    NFK,
    NGA,
    NIC,
    NIU,
    NLD,
    NOR,
    NPL,
    NRU,
    NZL,
    OMN,
    PAK,
    PAN,
    PCN,
    PER,
    PHL,
    PLW,
    PNG,
    POL,
    PRI,
    PRK,
    PRT,
    PRY,
    PSE,
    PYF,
    QAT,
    REU,
    ROU,
    RUS,
    RWA,
    SAU,
    SDN,
    SEN,
    SGP,
    SGS,
    SHN,
    SJM,
    SLB,
    SLE,
    SLV,
    SMR,
    SOM,
    SPM,
    SRB,
    STP,
    SUR,
    SVK,
    SVN,
    SWE,
    SWZ,
    SXM,
    SYC,
    SYR,
    TCA,
    TCD,
    TGO,
    THA,
    TJK,
    TKL,
    TKM,
    TLS,
    TON,
    TTO,
    TUN,
    TUR,
    TUV,
    TWN,
    TZA,
    UGA,
    UKR,
    UMI,
    URY,
    USA,
    UZB,
    VAT,
    VCT,
    VEN,
    VGB,
    VIR,
    VNM,
    VUT,
    WLF,
    WSM,
    YEM,
    ZAF,
    ZMB,
    ZWE,
}

impl T0399 {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "ABW" => Some(T0399::ABW),
            "AFG" => Some(T0399::AFG),
            "AGO" => Some(T0399::AGO),
            "AIA" => Some(T0399::AIA),
            "ALA" => Some(T0399::ALA),
            "ALB" => Some(T0399::ALB),
            "AND" => Some(T0399::AND),
            "ARE" => Some(T0399::ARE),
            "ARG" => Some(T0399::ARG),
            "ARM" => Some(T0399::ARM),
            "ASM" => Some(T0399::ASM),
            "ATA" => Some(T0399::ATA),
            "ATF" => Some(T0399::ATF),
            "ATG" => Some(T0399::ATG),
            "AUS" => Some(T0399::AUS),
            "AUT" => Some(T0399::AUT),
            "AZE" => Some(T0399::AZE),
            "BDI" => Some(T0399::BDI),
            "BEL" => Some(T0399::BEL),
            "BEN" => Some(T0399::BEN),
            "BES" => Some(T0399::BES),
            "BFA" => Some(T0399::BFA),
            "BGD" => Some(T0399::BGD),
            "BGR" => Some(T0399::BGR),
            "BHR" => Some(T0399::BHR),
            "BHS" => Some(T0399::BHS),
            "BIH" => Some(T0399::BIH),
            "BLM" => Some(T0399::BLM),
            "BLR" => Some(T0399::BLR),
            "BLZ" => Some(T0399::BLZ),
            "BMU" => Some(T0399::BMU),
            "BOL" => Some(T0399::BOL),
            "BRA" => Some(T0399::BRA),
            "BRB" => Some(T0399::BRB),
            "BRN" => Some(T0399::BRN),
            "BTN" => Some(T0399::BTN),
            "BVT" => Some(T0399::BVT),
            "BWA" => Some(T0399::BWA),
            "CAF" => Some(T0399::CAF),
            "CAN" => Some(T0399::CAN),
            "CCK" => Some(T0399::CCK),
            "CHE" => Some(T0399::CHE),
            "CHL" => Some(T0399::CHL),
            "CHN" => Some(T0399::CHN),
            "CIV" => Some(T0399::CIV),
            "CMR" => Some(T0399::CMR),
            "COD" => Some(T0399::COD),
            "COG" => Some(T0399::COG),
            "COK" => Some(T0399::COK),
            "COL" => Some(T0399::COL),
            "COM" => Some(T0399::COM),
            "CPV" => Some(T0399::CPV),
            "CRI" => Some(T0399::CRI),
            "CUB" => Some(T0399::CUB),
            "CUW" => Some(T0399::CUW),
            "CXR" => Some(T0399::CXR),
            "CYM" => Some(T0399::CYM),
            "CYP" => Some(T0399::CYP),
            "CZE" => Some(T0399::CZE),
            "DEU" => Some(T0399::DEU),
            "DJI" => Some(T0399::DJI),
            "DMA" => Some(T0399::DMA),
            "DNK" => Some(T0399::DNK),
            "DOM" => Some(T0399::DOM),
            "DZA" => Some(T0399::DZA),
            "ECU" => Some(T0399::ECU),
            "EGY" => Some(T0399::EGY),
            "ERI" => Some(T0399::ERI),
            "ESH" => Some(T0399::ESH),
            "ESP" => Some(T0399::ESP),
            "EST" => Some(T0399::EST),
            "ETH" => Some(T0399::ETH),
            "FIN" => Some(T0399::FIN),
            "FJI" => Some(T0399::FJI),
            "FLK" => Some(T0399::FLK),
            "FRA" => Some(T0399::FRA),
            "FRO" => Some(T0399::FRO),
            "FSM" => Some(T0399::FSM),
            "GAB" => Some(T0399::GAB),
            "GBR" => Some(T0399::GBR),
            "GEO" => Some(T0399::GEO),
            "GGY" => Some(T0399::GGY),
            "GHA" => Some(T0399::GHA),
            "GIB" => Some(T0399::GIB),
            "GIN" => Some(T0399::GIN),
            "GLP" => Some(T0399::GLP),
            "GMB" => Some(T0399::GMB),
            "GNB" => Some(T0399::GNB),
            "GNQ" => Some(T0399::GNQ),
            "GRC" => Some(T0399::GRC),
            "GRD" => Some(T0399::GRD),
            "GRL" => Some(T0399::GRL),
            "GTM" => Some(T0399::GTM),
            "GUF" => Some(T0399::GUF),
            "GUM" => Some(T0399::GUM),
            "GUY" => Some(T0399::GUY),
            "HKG" => Some(T0399::HKG),
            "HMD" => Some(T0399::HMD),
            "HND" => Some(T0399::HND),
            "HRV" => Some(T0399::HRV),
            "HTI" => Some(T0399::HTI),
            "HUN" => Some(T0399::HUN),
            "IDN" => Some(T0399::IDN),
            "IMN" => Some(T0399::IMN),
            "IND" => Some(T0399::IND),
            "IOT" => Some(T0399::IOT),
            "IRL" => Some(T0399::IRL),
            "IRN" => Some(T0399::IRN),
            "IRQ" => Some(T0399::IRQ),
            "ISL" => Some(T0399::ISL),
            "ISR" => Some(T0399::ISR),
            "ITA" => Some(T0399::ITA),
            "JAM" => Some(T0399::JAM),
            "JEY" => Some(T0399::JEY),
            "JOR" => Some(T0399::JOR),
            "JPN" => Some(T0399::JPN),
            "KAZ" => Some(T0399::KAZ),
            "KEN" => Some(T0399::KEN),
            "KGZ" => Some(T0399::KGZ),
            "KHM" => Some(T0399::KHM),
            "KIR" => Some(T0399::KIR),
            "KNA" => Some(T0399::KNA),
            "KOR" => Some(T0399::KOR),
            "KWT" => Some(T0399::KWT),
            "LAO" => Some(T0399::LAO),
            "LBN" => Some(T0399::LBN),
            "LBR" => Some(T0399::LBR),
            "LBY" => Some(T0399::LBY),
            "LCA" => Some(T0399::LCA),
            "LIE" => Some(T0399::LIE),
            "LKA" => Some(T0399::LKA),
            "LSO" => Some(T0399::LSO),
            "LTU" => Some(T0399::LTU),
            "LUX" => Some(T0399::LUX),
            "LVA" => Some(T0399::LVA),
            "MAC" => Some(T0399::MAC),
            "MAF" => Some(T0399::MAF),
            "MAR" => Some(T0399::MAR),
            "MCO" => Some(T0399::MCO),
            "MDA" => Some(T0399::MDA),
            "MDG" => Some(T0399::MDG),
            "MDV" => Some(T0399::MDV),
            "MEX" => Some(T0399::MEX),
            "MHL" => Some(T0399::MHL),
            "MKD" => Some(T0399::MKD),
            "MLI" => Some(T0399::MLI),
            "MLT" => Some(T0399::MLT),
            "MMR" => Some(T0399::MMR),
            "MNE" => Some(T0399::MNE),
            "MNG" => Some(T0399::MNG),
            "MNP" => Some(T0399::MNP),
            "MOZ" => Some(T0399::MOZ),
            "MRT" => Some(T0399::MRT),
            "MSR" => Some(T0399::MSR),
            "MTQ" => Some(T0399::MTQ),
            "MUS" => Some(T0399::MUS),
            "MWI" => Some(T0399::MWI),
            "MYS" => Some(T0399::MYS),
            "MYT" => Some(T0399::MYT),
            "NAM" => Some(T0399::NAM),
            "NCL" => Some(T0399::NCL),
            "NER" => Some(T0399::NER),
            "NFK" => Some(T0399::NFK),
            "NGA" => Some(T0399::NGA),
            "NIC" => Some(T0399::NIC),
            "NIU" => Some(T0399::NIU),
            "NLD" => Some(T0399::NLD),
            "NOR" => Some(T0399::NOR),
            "NPL" => Some(T0399::NPL),
            "NRU" => Some(T0399::NRU),
            "NZL" => Some(T0399::NZL),
            "OMN" => Some(T0399::OMN),
            "PAK" => Some(T0399::PAK),
            "PAN" => Some(T0399::PAN),
            "PCN" => Some(T0399::PCN),
            "PER" => Some(T0399::PER),
            "PHL" => Some(T0399::PHL),
            "PLW" => Some(T0399::PLW),
            "PNG" => Some(T0399::PNG),
            "POL" => Some(T0399::POL),
            "PRI" => Some(T0399::PRI),
            "PRK" => Some(T0399::PRK),
            "PRT" => Some(T0399::PRT),
            "PRY" => Some(T0399::PRY),
            "PSE" => Some(T0399::PSE),
            "PYF" => Some(T0399::PYF),
            "QAT" => Some(T0399::QAT),
            "REU" => Some(T0399::REU),
            "ROU" => Some(T0399::ROU),
            "RUS" => Some(T0399::RUS),
            "RWA" => Some(T0399::RWA),
            "SAU" => Some(T0399::SAU),
            "SDN" => Some(T0399::SDN),
            "SEN" => Some(T0399::SEN),
            "SGP" => Some(T0399::SGP),
            "SGS" => Some(T0399::SGS),
            "SHN" => Some(T0399::SHN),
            "SJM" => Some(T0399::SJM),
            "SLB" => Some(T0399::SLB),
            "SLE" => Some(T0399::SLE),
            "SLV" => Some(T0399::SLV),
            "SMR" => Some(T0399::SMR),
            "SOM" => Some(T0399::SOM),
            "SPM" => Some(T0399::SPM),
            "SRB" => Some(T0399::SRB),
            "STP" => Some(T0399::STP),
            "SUR" => Some(T0399::SUR),
            "SVK" => Some(T0399::SVK),
            "SVN" => Some(T0399::SVN),
            "SWE" => Some(T0399::SWE),
            "SWZ" => Some(T0399::SWZ),
            "SXM" => Some(T0399::SXM),
            "SYC" => Some(T0399::SYC),
            "SYR" => Some(T0399::SYR),
            "TCA" => Some(T0399::TCA),
            "TCD" => Some(T0399::TCD),
            "TGO" => Some(T0399::TGO),
            "THA" => Some(T0399::THA),
            "TJK" => Some(T0399::TJK),
            "TKL" => Some(T0399::TKL),
            "TKM" => Some(T0399::TKM),
            "TLS" => Some(T0399::TLS),
            "TON" => Some(T0399::TON),
            "TTO" => Some(T0399::TTO),
            "TUN" => Some(T0399::TUN),
            "TUR" => Some(T0399::TUR),
            "TUV" => Some(T0399::TUV),
            "TWN" => Some(T0399::TWN),
            "TZA" => Some(T0399::TZA),
            "UGA" => Some(T0399::UGA),
            "UKR" => Some(T0399::UKR),
            "UMI" => Some(T0399::UMI),
            "URY" => Some(T0399::URY),
            "USA" => Some(T0399::USA),
            "UZB" => Some(T0399::UZB),
            "VAT" => Some(T0399::VAT),
            "VCT" => Some(T0399::VCT),
            "VEN" => Some(T0399::VEN),
            "VGB" => Some(T0399::VGB),
            "VIR" => Some(T0399::VIR),
            "VNM" => Some(T0399::VNM),
            "VUT" => Some(T0399::VUT),
            "WLF" => Some(T0399::WLF),
            "WSM" => Some(T0399::WSM),
            "YEM" => Some(T0399::YEM),
            "ZAF" => Some(T0399::ZAF),
            "ZMB" => Some(T0399::ZMB),
            "ZWE" => Some(T0399::ZWE),
            _ => None,
        }
    }
}



pub struct VersionIdentifier {
    pub vid1: T0104,
    pub vid2: Option<T0399>,
    pub vid3: Option<CodedElement>,
}


